Cria a entidade formação
thesivis/mibanca pull request #11
Opened 2023-03-03 01:31 UTC by MarcosARGomes

Criação da entidade cliente utilizando o JPA que é o utilizado no projeto.

2023-03-03 01:41 UTC, RicGen10 requested changes, later dismissed
Ajuste os relacionamentos.

2023-03-03 01:41 UTC, RicGen10 commented on mibanca/src/main/java/br/ufmt/mibanca/formacao/Formacao.java
> +
Adicione os relacionamentos com tipo banca e curso sendo estes @ManyToOne.

Segue um exemplo:

@ManyToOne
private Curso curso;

2023-03-03 01:53 UTC, MarcosARGomes commented on mibanca/src/main/java/br/ufmt/mibanca/formacao/Formacao.java
> +
Relacionamentos adicionados.

2023-03-09 23:25 UTC, thesivis commented on mibanca/src/main/java/br/ufmt/mibanca/formacao/Formacao.java
> +
Espaços extras desnecessários

2023-03-09 23:26 UTC, thesivis commented on mibanca/src/main/java/br/ufmt/mibanca/formacao/Formacao.java
> +    @GeneratedValue (generator = "seq_formacao_id", strategy = GenerationType.SEQUENCE)
O nome do generator deve ser o name do @SequenceGenerator e não o sequenceName

2023-03-09 23:26 UTC, thesivis commented on mibanca/src/main/java/br/ufmt/mibanca/formacao/Formacao.java
> +    @Column(name="cargaHoraria")
Padronizar o nome das colunas no banco com _ ao invés de camelCase

2023-03-09 23:33 UTC, MarcosARGomes commented on mibanca/src/main/java/br/ufmt/mibanca/formacao/Formacao.java
> +
Alteração realizada

2023-03-09 23:33 UTC, MarcosARGomes commented on mibanca/src/main/java/br/ufmt/mibanca/formacao/Formacao.java
> +    @GeneratedValue (generator = "seq_formacao_id", strategy = GenerationType.SEQUENCE)
Alteração realizada

2023-03-09 23:33 UTC, MarcosARGomes commented on mibanca/src/main/java/br/ufmt/mibanca/formacao/Formacao.java
> +    @Column(name="cargaHoraria")
Alteração realizada

2023-03-09 23:36 UTC, thesivis approved these changes

2023-03-09 23:55 UTC, GostoZac approved these changes

2023-03-09 23:58 UTC, merged