Cria a entidade Pessoa
thesivis/mibanca pull request #12
Opened 2023-03-03 01:32 UTC by LuanCruz13

Este commit cria a entidade Pessoa utilizando o JPA que é o utilizado no projeto

2023-03-03 01:38 UTC, thaliakmo requested changes
Faltou o codigo

2023-03-03 01:43 UTC, isconaifa requested changes
faltou código

2023-03-09 23:26 UTC, isconaifa approved these changes

2023-03-09 23:30 UTC, thaliakmo approved these changes

2023-03-09 23:30 UTC, merged