Apresentacao
thesivis/mibanca pull request #16
Opened 2023-03-03 02:33 UTC by paulopoxoreo1984

2023-03-03 02:40 UTC, flpassun commented
Necessita revisão

2023-03-03 02:42 UTC, flpassun requested changes
Necessário avaliação.

2023-03-10 00:42 UTC, thesivis approved these changes

2023-03-10 00:47 UTC, flpassun commented
Aprovado

2023-03-10 00:47 UTC, flpassun approved these changes

2023-03-10 00:49 UTC, GostoZac commented on mibanca/src/main/java/br/ufmt/mibanca/apresentacao/Apresentacao.java
> +    @Column(name = "nome", length = 200)
isso seria pra chave estrangeira "id_banca", porém não é assim que se implementa, pode apagar

2023-03-10 00:50 UTC, GostoZac commented on mibanca/src/main/java/br/ufmt/mibanca/apresentacao/Apresentacao.java
> +    //private Cidade cidade;
faltou colocar comentário de banca e aluno para as futuras chaves estrangeiras

2023-03-10 00:51 UTC, merged

2023-03-10 00:51 UTC, GostoZac commented on mibanca/src/main/java/br/ufmt/mibanca/apresentacao/Apresentacao.java
> +     boolean situacao;
faltou colocar o @Column de data e situação

2023-03-10 00:51 UTC, GostoZac approved these changes