Cria avaliacao
thesivis/mibanca pull request #17
Opened 2023-03-03 02:38 UTC by flpassun

2023-03-03 02:42 UTC, GostoZac requested changes
falta atributos nota_avaliacao e comentario_avaliacao, e chave estrangeira para banca

2023-03-10 00:42 UTC, GostoZac approved these changes

2023-03-10 00:42 UTC, GostoZac commented on mibanca/src/main/java/br/ufmt/mibanca/avaliacao/Avaliacao.java
> +    private float nota_avaliacao;
faltou colocar os dados para o banco de dados pela JPA, segue exemplo:

@Column(name = "cargo", length = 200)
    private String cargo;
    @Column(name = "codMatricula")
    private int codMatricula;
    @Column(name = "intituicao", length = 200)
    private String instituicao;
    @Column(name = "endereco", length = 400)
    private String endereco;
    @Column(name = "email", length = 200)
    private String email;

2023-03-10 00:42 UTC, thesivis approved these changes

2023-03-10 00:42 UTC, merged