Cria a entidade Cidade
thesivis/mibanca pull request #7
Opened 2023-03-03 01:27 UTC by natlle

Este commit cria a entidade Cidade utilizando o JPA que é utilizado no projeto

2023-03-03 01:38 UTC, leogutierrezzz requested changes
Está faltando atributo cod_postal.

2023-03-03 02:16 UTC, jogodoy8 requested changes
Olá!
Será necessário você revisar, porque tem um cliente que não existe e também não encontrei o código postal.

2023-03-03 02:26 UTC, natlle commented
Ajustado, por favor revisar

2023-03-09 23:09 UTC, leogutierrezzz approved these changes

2023-03-09 23:24 UTC, jogodoy8 requested changes

2023-03-09 23:24 UTC, jogodoy8 commented on mibanca/src/main/java/br/ufmt/mibanca/cidade/Cidade.java
> +    private static final class Estado {}
Olá!
Esta classe deverá ser implementada pelo estado.

2023-03-09 23:37 UTC, natlle commented
Atualização feita, por favor revisar novamente.

2023-03-09 23:43 UTC, jogodoy8 approved these changes

2023-03-10 00:12 UTC, merged