Cria a entidade Instituto
thesivis/mibanca pull request #9
Opened 2023-03-03 01:29 UTC by leogutierrezzz

Cria a entidade Instituto utilizando o JPA que é utilizado no projeto.

2023-03-03 01:34 UTC, RicGen10 commented
Mude a referencia do join de um atributo primitivo para uma classe

2023-03-03 01:35 UTC, RicGen10 requested changes

2023-03-03 01:35 UTC, RicGen10 commented on mibanca/src/main/java/br/ufmt/mibanca/instituto/Instituto.java
> +    // @ManyToOne
Ao invés de utilizar um tipo primitivo coloque:

private Cidade cidade;

2023-03-03 01:36 UTC, RicGen10 requested changes, later dismissed
Ajuste o join de institudo com cidade

2023-03-03 01:36 UTC, RicGen10 commented on mibanca/src/main/java/br/ufmt/mibanca/instituto/Instituto.java
> +    // private int idCidade;
Mude do tipo primitivo int para um objeto.

private Cidade cidade;

2023-03-09 23:59 UTC, natlle approved these changes
Revisado e aprovado.

2023-03-10 00:06 UTC, thesivis commented on mibanca/src/main/java/br/ufmt/mibanca/instituto/Instituto.java
> +    @Column(name = "Universidade", length = 100)
No banco vamos utilizar tudo minusculo

2023-03-10 00:06 UTC, thesivis commented on mibanca/src/main/java/br/ufmt/mibanca/instituto/Instituto.java
> +    @Column(name = "Ativo")
Minúsculo

2023-03-10 00:15 UTC, thesivis approved these changes

2023-03-10 00:17 UTC, merged